### PR TITLE
Improve installation guide & replaced old functions

### PR DESCRIPTION
**Pull request by reichherzerp**
#### Installation documentation
- explain additional flasg (e.g. FAST_WAVES, SIMD, OMP_SCHEDULE)
- correct broken links
- more consistency between both installation methods

#### Other
- used `checkGridRequirements` in `SimpleGridTurbulence` instead of old checks

### CODE REVIEW

**Comment by lukasmerten** [comment]
Hi Patrick 
Thi PR seems to break tests for the turbulent magnetic field.
I guess this comes from your switch to CheckGridRequirements in SimpleGridTurbulence.
Please adjust the test accordingly - it seems the test is expected deprecation warnings, which are of ourse no longer thrown in checkGridRequrements.

**Review by lukasmerten — CHANGES_REQUESTED** [review]
Update tests of turbulent grids.

**Comment by lukasmerten** [comment]
The rest looks good to me.

**Comment by reichherzerp** [comment]
Thanks @lukasmerten, there was the check for lMin > lMax missing... I updated the checkGridRequirements function accordingly.

**Review by lukasmerten — APPROVED** [review]

**Pull request merged**
